### ISSUE TITLE
Employee API : null data returns.

### ISSUE THREAD

**Issue by purvathakkar** [square/connect-java-sdk#52]
while using employee api no data returns, 
```   
        V1EmployeesApi roles = new V1EmployeesApi();
        CompleteResponse<List<V1EmployeeRole>> employeeRolesResponse;
        List<V1EmployeeRole> employeeRolesList = new ArrayList<>();
        String batchToken = null;
        do {
            employeeRolesResponse = roles.listEmployeeRolesWithHttpInfo(SortOrder.ASC.name(), 100, batchToken);
            employeeRolesList.addAll(employeeRolesResponse.getData());
            batchToken = employeeRolesResponse.getBatchToken();
        } while (batchToken != null);
```
I don't know if I am doing something wrong.
Thank you.

**Comment by StephenJosey** [comment]
@purvathakkar terribly sorry for the delay, somehow this issue slipped through. To assist with your issue, you should pass `null` rather than `""` as those parameters. So essnetially it would look like this:
`empResponse = v1EmployeesApi.listEmployeesWithHttpInfo(SortOrder.ASC.name(), null, null, null, 
           null, null, null, 100, batchToken);`

I've confirmed that this gives back the correct results for my own account. Please let me know if you have further issues, and I apologize again for the long delay.

**Comment by purvathakkar** [comment]
Thank you stephen :)
